import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import Link from "next/link";
import { useEffect, useState } from "react";
import axios from "axios";
import { Slide } from "react-slideshow-image";
import AOS from "aos";
import "aos/dist/aos.css";

import "react-slideshow-image/dist/styles.css";
import { blue } from "@mui/material/colors";
import server from "@/axois/server";

const spanStyle = {
  padding: "20px",
  background: "#efefef",
  color: "#000000",
};

const divStyle = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  backgroundSize: "cover",
  height: "100%",
  width: "100vw",
};




export default function Home({ image }) {



  useEffect(() => {
    AOS.init({ duration: 1000 });

  }, []);


  const [specialMenu, setSpecialMenu] = useState([]);
  const loadData = async () => {
    try {
      const res = await server.get("/api/product?special_menu=special_menu");
      if (res.status === 200) {
        setSpecialMenu(res.data.menu);
      }
    } catch (error) {
      console.log(error);
    }
  };

  //Counter for Count
  const counter = {
    activeUser: "50",
    totalUser: "1",
    toalMenu: "20",
    toalOrder: "300",
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleClick = (menuItem) => {
    setCurrent(menuItem);
  };

  const [current, setCurrent] = useState('all_menu');
  const renderMenu = () => {
    switch (current) {
      case 'all_menu':
        return (
          <>

          </>

        )
      case 'burger':
        return (
          <>

          </>

        )
      case 'pizza':
        return (
          <>

          </>

        )
      case 'all_menu':
        return (
          <>

          </>

        )

      default:
        return <div>Data not found</div>;
    }
  }
  return (
    <>
      <Head>
        <title>Restaurent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>

        <div className="slide-container">
          <Slide>
            {image && image.map((item, index) => (
              <div className="w-screen h-screen m-auto">
                <div key={index} style={{
                  ...divStyle,
                  backgroundImage: `url(/uploads/${item.image})`,
                }}>

                </div>
              </div>
            ))}
          </Slide>
        </div>

        {/* About section */}
        <div class="flex flex-col md:flex-row justify-center items-center px-10 w-full h-screen">
          <div class="w-full md:w-1/3 mb-8 md:mb-0">
            <h1 class="font-bold text-3xl mb-4">About Our Story</h1>
            <p class="text-gray-700">Who are in extremely love with eco friendly system. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <div className="my-5">
              <Link href="/Menu" className="button mx-3">View Our Menu</Link >
            </div>
          </div>
          <div class="w-full md:w-auto md:ml-5">
            <img src="/photos/back.jpeg" class="overflow-hidden" width={500} height={500} alt="About Our Story" />
          </div>
        </div>

        {/* Offer  */}
        <div>
          <div className="max-w-full container flex flex-col sm:flex-row justify-around p-8 sm:p-16 bg-gray-200">
            <div className="offer Item bg-indigo-950 w-full sm:w-1/3 flex flex-col sm:flex-row justify-around items-center">
              <div className="offer_image rounded-full overflow-hidden">
                <Image className="w-20 h-20 sm:w-40 sm:h-40" src="https://www.shutterstock.com/image-photo/fresh-tasty-burger-isolated-on-600nw-705104968.jpg" height={500} width={500} alt="" />
              </div>
              <div className="offer_info text-center sm:text-left mt-4 sm:mt-0">
                <h3 className="text-white p-1">Tasty Thursday</h3>
                <h1 className="text-white p-2">20%</h1>
                <button className="bg-rose-600 hover:bg-rose-900 text-white font-bold py-2 px-4 rounded">Order Now</button>
              </div>
            </div>
            <div className="offer Item bg-indigo-950 w-full sm:w-1/3 flex flex-col sm:flex-row justify-around items-center mt-4 sm:mt-0">
              <div className="offer_image rounded-full overflow-hidden">
                <Image className="w-20 h-20 sm:w-40 sm:h-40" src="https://www.shutterstock.com/image-photo/fresh-tasty-burger-isolated-on-600nw-705104968.jpg" height={500} width={500} alt="" />
              </div>
              <div className="offer_info text-center sm:text-left mt-4 sm:mt-0">
                <h3 className="text-white p-1">Tasty Thursday</h3>
                <h1 className="text-white p-2">20%</h1>
                <button className="bg-rose-600 hover:bg-rose-900 text-white font-bold py-2 px-4 rounded">Order Now</button>
              </div>
            </div>
          </div>
        </div>


        {/* Special Item */}
        <div className="max-w-full">
          <h5 className="text-center text-3xl py-2">Explore</h5>
          <h2 className="text-center text-4xl font-bold py-4">Our Special Menu</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-4 justify-items-center py-3">
            {specialMenu &&
              specialMenu.map((item, index) => {

                return (
                  <div
                    data-aos="zoom-out"
                    className="bg-white p-4 rounded-lg shadow-md dark:bg-surface-dark dark:text-white box_shadow"
                    key={index}
                  >
                    <div className="flex flex-col items-center px-5 py-3">
                      <div className="mb-3">
                        <Image
                          className="rounded-full h-32 w-32 sm:h-40 sm:w-40"
                          src={`/uploads/${item.image}`}
                          alt={item.description}
                          height={200}
                          width={200}
                        />
                      </div>

                      <div className="info_product text-center">
                        <h2 className="font-bold uppercase">{item.name}</h2>
                        <p className="ml-2">Rs.{item.price}</p>
                        <div className="flex justify-center items-center mb-2">
                          <p className="">
                            <i className="fa fa-star" aria-hidden="true"></i>
                            <i className="fa fa-star" aria-hidden="true"></i>
                            <i className="fa fa-star" aria-hidden="true"></i>
                            <i className="fa fa-star" aria-hidden="true"></i>
                            <i className="fa fa-star-o" aria-hidden="true"></i>
                          </p>
                        </div>

                        <div>
                          <Link href={`/Menu?category=${item.category}`}>
                            <i className="bg-rose-600 hover:bg-rose-900 text-white font-bold py-2 px-4 rounded fa fa-arrow-circle-o-right text-2xl font-bold" aria-hidden="true"></i>
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
          </div>
        </div>




        {/* Advertisement */}
        <div className="bg-gray-200 flex flex-col justify-center items-center h-screen md:flex-row">
          <div className="md:w-1/2">
            <Image className="w-full h-auto" src="https://img.freepik.com/free-photo/grilled-gourmet-burger-with-cheese-tomato-onion-french-fries-generated-by-artificial-intelligence_25030-63181.jpg" width={500} height={500} alt="" />
          </div>
          <div className="md:w-1/2 px-4 py-8 md:py-0">
            <h3 className="  text-center md:text-left">We Are Feane</h3>
            <p className="text-center md:text-left">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All</p>
            <div className="flex justify-center md:justify-start">
              <button className=" button bg-rose-600 hover:bg-rose-900 font-bold py-2 px-4 rounded mt-4 md:mt-8">
                Read More
              </button>
            </div>
          </div>
        </div>




      </Layout >

    </>
  );
}
export async function getServerSideProps() {
  try {
    const res = await server.get('http://localhost:3000/api/sliderImage?sliderimage=three');
    if (res.status === 200) {
      const image = res.data;

      return {
        props: {
          image
        }
      };
    } else {
      // Handle other HTTP status codes if needed
      return {
        props: {
          image: [] // Return empty array or handle accordingly
        }
      };
    }
  } catch (error) {
    console.error("Error fetching slider images:", error);
    return {
      props: {
        image: [] // Return empty array or handle accordingly
      }
    };
  }
}
